---
- name: App Server
  hosts: web
  sudo: yes
  user: root

  roles:
    - common
    - firewall
    - ruby
    - nginx
    - unicorn
    - upstart
    - monit
    - postgresql

# Use this block to a different node
#- name: Database Server
#  hosts: db
#  sudo: yes
#  user: root
#
#  roles:
#    - common
#    - postgresql
