---
- name: Install extra packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - git
    - ufw

- name: Create user for deploy
  user: name=deploy group=www-data comment="Deploy user"
  tags: create_user
